const {test}=require('node:test');const assert=require('node:assert/strict');
const {HomeStore,emptyData}=require('./store.cjs');
const task=note=>({id:'t1',title:'任务',date:'2026-09-05',note,importance:60,urgency:30,done:false,planId:'',schedule:null,nodes:[]});
test('starts empty and rejects unknown or corrupt data without writing',()=>{let writes=0;const s=new HomeStore(async()=>writes++);assert.equal(s.data.tasks.length,0);assert.throws(()=>s.load({schemaVersion:99}));assert.equal(writes,0);});
test('serializes writes and can retry after a failed write',async()=>{const writes=[];let fail=true;const s=new HomeStore(async d=>{await new Promise(r=>setTimeout(r,10));if(fail){fail=false;throw Error('disk');}writes.push(d);});const a=emptyData();a.tasks=[task('a.md')];await assert.rejects(s.saveUI(a));a.tasks[0].title='第二次';const p=s.saveUI(a);a.tasks[0].title='第三次';const q=s.saveUI(a);await Promise.all([p,q]);assert.equal(writes[0].data.tasks[0].title,'第二次');assert.equal(writes[1].data.tasks[0].title,'第三次');});
test('file and folder rename persist associations and recent history',async()=>{let last;const s=new HomeStore(async d=>last=d);const d=emptyData();d.tasks=[task('课程/摘要.md')];await s.saveUI(d);await s.opened('课程/摘要.md',123);await s.rename('课程','资料');assert.equal(last.data.tasks[0].note,'资料/摘要.md');assert.equal(last.recent['资料/摘要.md'],123);await s.rename('资料/摘要.md','资料/总结.md');assert.equal(last.data.tasks[0].note,'资料/总结.md');});
test('delete preserves a missing task link and removes recent entry',async()=>{const s=new HomeStore(async()=>{});const d=emptyData();d.tasks=[task('摘要.md')];await s.saveUI(d);await s.opened('摘要.md');await s.deleted('摘要.md');assert.equal(s.data.tasks[0].note,'摘要.md');assert.equal(s.recent['摘要.md'],undefined);});
test('reusing an old filename links the newly selected file, not rename history',async()=>{const s=new HomeStore(async()=>{});const d=emptyData();d.tasks=[task('a.md')];await s.saveUI(d);await s.rename('a.md','b.md');d.tasks[0].note='a.md';await s.saveUI(d);assert.equal(s.data.tasks[0].note,'a.md');});
test('restores saved state and migrates a preview snapshot',()=>{const s=new HomeStore(async()=>{});const d=emptyData();d.tasks=[task('笔记.md')];d.files=[{name:'笔记.md',modified:1,opened:2}];s.load(d);assert.equal(s.recent['笔记.md'],2);const restored=new HomeStore(async()=>{});restored.load(s.snapshot());assert.equal(restored.data.tasks[0].note,'笔记.md');assert.equal(restored.data.files.length,0);});
test('startup and style settings survive task saves and restart; old data gains defaults',async()=>{let last;const s=new HomeStore(async value=>last=value);s.load({schemaVersion:1,data:emptyData(),recent:{}});assert.deepEqual(s.settings,{openOnStartup:true,style:'studio'});await s.setPreferences({openOnStartup:false,style:'garden'});await s.saveUI(emptyData());const restored=new HomeStore(async()=>{});restored.load(last);assert.deepEqual(restored.settings,{openOnStartup:false,style:'garden'});});

test('component selection preserves the new plans widget and an intentionally empty layout',async()=>{let last;const s=new HomeStore(async value=>last=value);await s.setPreferences({widgets:['plans','today','notes']});await s.saveUI(emptyData());const restored=new HomeStore(async()=>{});restored.load(last);assert.deepEqual(restored.settings.widgets,['plans','today','notes']);await s.setPreferences({widgets:[]});restored.load(last);assert.deepEqual(restored.settings.widgets,[]);last.settings.widgets=['plans','unknown','plans','notes'];restored.load(last);assert.deepEqual(restored.settings.widgets,['plans','notes']);});

test('legacy data gains empty review fields without enrolling existing notes',()=>{const old=emptyData();delete old.reviews;delete old.reviewRevision;old.files=[{name:'已有.md',modified:1,opened:1}];const s=new HomeStore(async()=>{});s.load(old);assert.deepEqual(s.reviews(),{reviews:[],reviewRevision:0});});
test('new Markdown notes enroll once, opt-out prevents enrollment, and settings survive restart',async()=>{let last;const s=new HomeStore(async d=>last=d);await s.created('新笔记.md','2026-01-31');await s.created('新笔记.md','2026-01-31');await s.created('附件.png','2026-01-31');assert.equal(s.data.reviews.length,1);assert.equal(s.data.reviews[0].due,'2026-02-01');await s.setPreferences({reviewNewNotes:false,widgets:['ebbinghaus','notes'],style:'slate'});await s.created('不加入.md','2026-01-31');assert.equal(s.data.reviews.length,1);const restored=new HomeStore(async()=>{});restored.load(last);assert.equal(restored.settings.reviewNewNotes,false);assert.equal(restored.settings.style,'slate');assert.deepEqual(restored.settings.widgets,['ebbinghaus','notes']);});
test('review completion persists across restart and rejects a duplicate stage token',async()=>{let last;const s=new HomeStore(async d=>last=d);await s.created('记忆.md','2026-12-30');const first=s.data.reviews[0],action={type:'complete',id:first.id,stage:first.stage,due:first.due};await s.reviewAction(action,'2027-01-10');await s.reviewAction(action,'2027-01-10');const restored=new HomeStore(async()=>{});restored.load(last);assert.equal(restored.data.reviews[0].stage,1);assert.equal(restored.data.reviews[0].due,'2027-01-13');assert.equal(restored.data.reviewRevision,2);});
test('host review changes survive stale task saves and task undo snapshots',async()=>{const s=new HomeStore(async()=>{});const stale=emptyData();await s.created('学习/一.md','2026-01-31');await s.saveUI(stale);assert.equal(s.data.reviews.length,1);await s.rename('学习','知识');const snapshot=JSON.parse(JSON.stringify(s.data));await s.deleted('知识');snapshot.tasks=[task('旧快照.md')];await s.saveUI(snapshot);assert.deepEqual(s.data.reviews,[]);assert.equal(s.data.tasks[0].title,'任务');assert.equal(s.data.reviewRevision,3);});
test('explicit backup restore replaces review data with a new revision, ordinary save does not',async()=>{const s=new HomeStore(async()=>{});await s.created('备份.md','2026-01-31');const backup=JSON.parse(JSON.stringify(s.data));await s.deleted('备份.md');await s.saveUI(backup);assert.equal(s.data.reviews.length,0);await s.restoreUI(backup);assert.equal(s.data.reviews[0].path,'备份.md');assert.equal(s.data.reviewRevision,3);await s.reconcileReviews([]);assert.equal(s.data.reviews.length,0);assert.equal(s.data.reviewRevision,4);});
